project:
  type: website
  output-dir: docs

website:
  title: "Exploit.se"
  description: "Writeups and articles about cyber security / hacking."
  site-url: https://exploit.se
  site-path: 'docs'
  favicon: "favicon.ico"
  google-analytics: G-XVW5CQ7DG5
  navbar:
    logo: "static/exploit_white-orange.png"
    title: false
    right:
      - text: Writeups
        href: writeups.qmd
      - text: Notes
        href: "https://0xpthree.gitbook.io/notes"
      - text: About
        href: about.qmd
  page-footer:
    center:
      - text: "Â© 2024 0xPThree - All Rights Reserved."
    right:
      - icon: signal
        href: https://signal.me/#eu/PjVScis0spvu9_S_xNysergThKuqsWQFOwQ7xisr7HJgaJT69xC0Ku2fo3Ng0B1
      - icon: github
        href: https://github.com/0xpthree
      - icon: rss
        href: index.xml


format:
  html:
    theme: cosmo
    css: 
      - scss/styles.css
      - scss/bootstrap-dark.min.css
      - scss/quarto-syntax-highlighting-dark.css
      - scss/bootstrap-icons.css
      
editor: visual
